name: CI for ArgMultiLevelCache

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: windows-latest  # 支持 .NET Framework 构建
    strategy:
      matrix:
        target-framework: ['net472', 'net6.0', 'net7.0']
        dotnet-version: ['6.0.x', '7.0.x']

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --configuration Release

    - name: Run tests
      run: dotnet test --configuration Release

    - name: Pack library (NuGet)
      if: github.ref == 'refs/heads/main'
      run: |
        dotnet pack src/ArgMultiLevelCache.csproj -c Release

    - name: Upload Artifacts (for manual inspection)
      if: github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@v3
      with:
        name: nuget-packages
        path: ./artifacts/
